
/* eslint-disable no-irregular-whitespace */
/* eslint-disable react/jsx-no-useless-fragment */
import React from 'react';
import classes from './Terms.module.css';

function PrivacyPolicy () {
  return (
    <>
      <div className={classes.box}>
        <div className={classes.content}>
          <h4 className={classes.content__title}>Opspad Privacy Policy</h4>
          <p className={classes.child__title}>
            v.1 - Updated November 17th 2022
          </p>
          <h1 className={classes.h1}>INTRODUCTION</h1>
          <h3 className={classes.h3}> Welcome to OPS Pad.</h3>
          <p>
            <p>
              OPS Pad operates with its major objective in the safety of
              customers privacy most especially when making use of our services
              or accessing websites. Our Privacy Policy governs your visit to
              our application as well as your visit to opspad.com our website,
              and explains how we collect, safeguard and disclose information
              that results from your use of our Service.
            </p>
            <p>
              We use your data to provide and improve Service. By using Service,
              you agree to the collection and use of information in accordance
              with this policy. Unless otherwise defined in this Privacy Policy,
              the terms used in this Privacy Policy have the same meanings as in
              our Terms and Conditions. Our Terms and Conditions govern all use
              of our Service and together with the Privacy Policy constitutes
              your agreement with us.
            </p>
          </p>
          <h1 className={classes.h1}>COLLECTION OF INFORMATION</h1>
          <h5>Personal Data</h5>
          <p>
            Personal Data is defined as information that can be used on its own
            or with other information to identify, contact, or locate a single
            person, or to identify an individual in context. Personal data
            collected remains secure and safe away from reach of hackers or even
            the government. All information which is gotten in most of our
            interactions, if directly or indirectly it remains safe and sound.
            <ul className={classes.list}>
              <li>
                <span className={classes.span}>USAGE DATA </span> is data
                collected automatically either generated by the use of Service
                or from Service infrastructure itself (for example, the duration
                of a page visit).
              </li>
              <li>
                <span className={classes.span}>COOKIES</span> are small files
                stored on your device (computer or mobile device).
              </li>{' '}
              <li>
                <span className={classes.span}>DATA CONTROLLER </span> means a
                natural or legal person who (either alone or jointly or in
                common with other persons) determines the purposes for which and
                the manner in which any personal data are, or are to be,
                processed. For the purpose of this Privacy Policy, we are a Data
                Controller of your data.
              </li>{' '}
              <li>
                <span className={classes.span}>
                  DATA PROCESSORS (OR SERVICE PROVIDERS)
                </span>{' '}
                means any natural or legal person who processes the data on
                behalf of the Data Controller. We may use the services of
                various Service Providers in order to process your data more
                effectively.
              </li>{' '}
              <li>
                <span className={classes.span}>DATA SUBJECT</span> is any living
                individual who is the subject of Personal Data.
              </li>
              <li>
                <span className={classes.span}>THE USER</span> is the individual
                using our Service. The User corresponds to the Data Subject, who
                is the subject of Personal Data.
              </li>
            </ul>
          </p>
          <h5>Information received from you directly</h5>
          <p>
            <p>
              We collect several different types of information for various
              purposes to provide and improve our Service to you.
            </p>

            <p>
              collects and stores information during the registration of
              products, the creation of online profiles, the application via our
              website and any contact for support or other matters (e.g. contact
              or comment forms, telephone contact). Examples of information
              transmitted by you;
            </p>
          </p>
          <div>
            <ul className={classes.list}>
              <li>Name, address, phone number, email address</li>
              <li>IP addresses</li>
              <li>Billing and other purchasing and shipping information;</li>
              <li>
                Records of transactions, including purchases, inquiries and
                service requests;
              </li>
              <li>
                Authentication data such as user name and password to verify
                access.
              </li>
              <li>
                Application Data, CVs, profiles, pictures (additional Job
                Applicant Data Policy in place)
              </li>
            </ul>
          </div>
          <h1 className={classes.h1}>Types of Data Collected</h1>
          <h5>Personal Data</h5>
          <p>
            While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you (“Personal Data”). Personally, identifiable information
            may include, but is not limited to:
            <ul className={classes.numlist}>
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Address, Country, State, Province, ZIP/Postal code, City</li>
              <li>Cookies and Usage Data</li>
            </ul>
            <p>
              We may use your Personal Data to contact you with newsletters,
              marketing or promotional materials and other information that may
              be of interest to you. You may opt out of receiving any, or all,
              of these communications from us by following the unsubscribe link.
            </p>
          </p>
          <h5>Usage Data</h5>
          <p>
            We may also collect information that your browser sends whenever you
            visit our Service or when you access Service by or through any
            device. This Usage Data may include information such as your
            computer’s Internet Protocol address (e.g. IP address), browser
            type, browser version, the pages of our Service that you visit, the
            time and date of your visit, the time spent on those pages, unique
            device identifiers and other diagnostic data. When you access
            Service with a device, this Usage Data may include information such
            as the type of device you use, your device unique ID, the IP address
            of your device, your device operating system, the type of Internet
            browser you use, unique device identifiers and other diagnostic
            data.
          </p>
          <h5>Location Data</h5>
          <p>
            We may use and store information about your location if you give us
            permission to do so. We use this data to provide features of our
            Service, to improve and customize our Service. You can enable or
            disable location services when you use our Service at any time by
            way of your device settings.
          </p>
          <h5>Tracking Cookies Data</h5>
          <p>
            We use cookies and similar tracking technologies to track the
            activity on our Service and we hold certain information. Cookies are
            files with a small amount of data which may include an anonymous
            unique identifier. Cookies are sent to your browser from a website
            and stored on your device. Other tracking technologies are also used
            such as beacons, tags and scripts to collect and track information
            and to improve and analyze our Service.
            <p>
              You can instruct your browser to refuse all cookies or to indicate
              when a cookie is being sent. However, if you do not accept
              cookies, you may not be able to use some portions of our Service.
            </p>
            <div className={classes.span}>Examples of Cookies we use:</div>
            <ul className={classes.numlist}>
              <li>
                <span className={classes.span}>Session Cookies: </span> We use
                Session Cookies to operate our Service.
              </li>
              <li>
                <span className={classes.span}>Preference Cookies: </span> We
                use Preference Cookies to remember your preferences and various
                settings.
              </li>
              <li>
                <span className={classes.span}>Security Cookies: </span> We use
                Security Cookies for security purposes.
              </li>
              <li>
                <span className={classes.span}>Advertising Cookies: </span>{' '}
                Advertising Cookies are used to serve you with advertisements
                that may be relevant to you and your interests.
              </li>
            </ul>
          </p>
          <h5>Other Data</h5>
          <p>
            While using our Service, we may also collect the following
            information: sex, age, date of birth, place of birth, passport
            details, citizenship, registration at place of residence and actual
            address, telephone number (work, mobile), details of documents on
            education, qualification, professional training, employment
            agreements, NDA agreements, information on bonuses and compensation,
            information on marital status, family members, social security (or
            other taxpayer identification) number, office location and other
            data.
          </p>
          <h4>Use of Data</h4>
          <p>OPS Pad uses the collected data for various purposes:</p>
          <ul className={classes.numlist}>
            <li>To provide and maintain our Service;</li>
            <li>To notify you about changes to our Service;</li>
            <li>
              To allow you to participate in interactive features of our Service
              when you choose to do so;
            </li>
            <li>To provide customer support;</li>
            <li>
              To gather analysis or valuable information so that we can improve
              our Service;
            </li>
            <li>
              To monitor the usage of our Service; To detect, prevent and
              address technical issues;
            </li>
            <li>To fulfil any other purpose for which you provide it;</li>
            <li>
              To carry out our obligations and enforce our rights arising from
              any contracts entered into between you and us, including for
              billing and collection;
            </li>
            <li>
              To provide you with notices about your account and/or
              subscription, including expiration and renewal notices,
              email-instructions, etc.;
            </li>
            <li>
              To provide you with news, special offers and general information
              about other goods, services and events which we offer that are
              similar to those that you have already purchased or enquired about
              unless you have opted not to receive such information;
            </li>
            <li>
              In any other way we may describe when you provide the information;
            </li>
            <li>For any other purpose with your consent.</li>
          </ul>
          <h4>Retention of Data</h4>
          <p>
            We will retain your Personal Data only for as long as is necessary
            for the purposes set out in this Privacy Policy. We will retain and
            use your Personal Data to the extent necessary to comply with our
            legal obligations (for example, if we are required to retain your
            data to comply with applicable laws), resolve disputes, and enforce
            our legal agreements and policies. <br />
            We will also retain Usage Data for internal analysis purposes. Usage
            Data is generally retained for a shorter period, except when this
            data is used to strengthen the security or to improve the
            functionality of our Service, or we are legally obligated to retain
            this data for longer time periods.
          </p>
          <h4>Transfer of Data</h4>
          <p>
            Your information, including Personal Data, may be transferred to –
            and maintained on – computers located outside of your state,
            province, country or other governmental jurisdiction where the data
            protection laws may differ from those of your jurisdiction. If you
            are located outside Nigeria and choose to provide information to us,
            please note that we transfer the data, including Personal Data, to
            Nigeria and process it there. Your consent to this Privacy Policy
            followed by your submission of such information represents your
            agreement to that transfer. <br />
            OPS Pad will take all the steps reasonably necessary to ensure that
            your data is treated securely and in accordance with this Privacy
            Policy and no transfer of your Personal Data will take place to an
            organization or a country unless there are adequate controls in
            place including the security of your data and other personal
            information.
          </p>
          <h4>Data Protection for Minors</h4>
          <p>
            The Opspad website as well as its contents, services and offers are
            not directed at children or minors. Accordingly, Opspad does not
            want and does not assume that any information collected on the
            Opspad website or any forum will be personal data pertaining to
            children or minors. Any data which is identified as belonging to a
            child or minor is subject to immediate deletion.
          </p>
          <h4>Business Transaction</h4>
          <p>
            If we or our subsidiaries are involved in a merger, acquisition or
            asset sale, your Personal Data may be transferred.
          </p>
          <h4>Other cases. We may disclose your information also:</h4>
          <ul className={classes.numlist}>
            <li>To our subsidiaries and affiliates;</li>
            <li>
              To contractors, service providers, and other third parties we use
              to support our business;
            </li>
            <li>To fulfill the purpose for which you provide it;</li>
            <li>
              For the purpose of including your company’s logo on our website;
            </li>
            <li>With your consent in any other cases;</li>
            <li>
              If we believe disclosure is necessary or appropriate to protect
              the rights, property, or safety of the Company, our customers, or
              others.
            </li>
          </ul>
          <h4>Security of Data</h4>
          <p>
            The security of your data is important to us but remember that no
            method of transmission over the Internet or method of electronic
            storage is 100% secure. While we strive to use commercially
            acceptable means to protect your Personal Data, we cannot guarantee
            its absolute security.
          </p>
          <h4>Services Providers</h4>
          <p>
            We may employ third party companies and individuals to facilitate
            our Service, provide Service on our behalf, perform Service-related
            services or assist us in analyzing how our Service is used. These
            third parties have access to your Personal Data only to perform
            these tasks on our behalf and are obligated not to disclose or use
            it for any other purpose.
          </p>

          <h4>
            Your Data Protection Rights Under General Data Protection Regulation
            (GDPR)
          </h4>
          <p>
            <p>
              If you are a resident of the European Union (EU) and European
              Economic Area (EEA), you have certain data protection rights,
              covered by GDPR. <br /> We aim to take reasonable steps to allow
              you to correct, amend, delete, or limit the use of your Personal
              Data. <br /> If you wish to be informed what Personal Data we hold
              about you and if you want it to be removed from our systems,
              please email us at aekhoragbon@gmail.com. <br />
              In certain circumstances, you have the following data protection
              rights:
            </p>
            <ul className={classes.numlist}>
              <li>
                the right to access, update or to delete the information we have
                on you;
              </li>
              <li>
                the right of rectification. You have the right to have your
                information rectified if that information is inaccurate or
                incomplete;
              </li>
              <li>
                the right to object. You have the right to object to our
                processing of your Personal Data;
              </li>
              <li>
                the right of restriction. You have the right to request that we
                restrict the processing of your personal information;
              </li>
              <li>
                the right to data portability.You have the right to be provided
                with a copy of your Personal Data in a structured,
                machine-readable and commonly used format;
              </li>
              <li>
                the right to withdraw consent. You also have the right to
                withdraw your consent at any time where we rely on your consent
                to process your personal information;
              </li>
            </ul>
            <p>
              Please note that we may ask you to verify your identity before
              responding to such requests. Please note, we may not able to
              provide Service without some necessary data. <br />
              You have the right to complain to a Data Protection Authority
              about our collection and use of your Personal Data. For more
              information, please contact your local data protection authority
              in the European Economic Area (EEA).
            </p>
          </p>
          <h4>Behavioural Remarketing</h4>
          <p>
            We may use remarketing services to advertise on third party websites
            to you after you visited our Service. We and our third-party vendors
            use cookies to inform, optimise and serve ads based on your past
            visits to our Service.
          </p>
          <h4>Payments</h4>
          <p>
            We may provide paid products and/or services within Service. In that
            case, we use third-party services for payment processing (e.g.
            payment processors). We will not store or collect your payment card
            details. That information is provided directly to our third-party
            payment processors whose use of your personal information is
            governed by their Privacy Policy. These payment processors adhere to
            the standards set by PCI-DSS as managed by the PCI Security
            Standards Council, which is a joint effort of brands like Visa,
            Mastercard, American Express and Discover. PCI-DSS requirements help
            ensure the secure handling of
          </p>
          <h4>Links to other Sites</h4>
          <p>
            Our Service may contain links to other sites that are not operated
            by us. If you click a third party link, you will be directed to that
            third party’s site. We strongly advise you to review the Privacy
            Policy of every site you visit. We have no control over and assume
            no responsibility for the content, privacy policies or practices of
            any third party sites or services. For example, the outlined privacy
            policy has been made using PolicyMaker.io, a free tool that helps
            create high-quality legal documents. PolicyMaker’s privacy policy
            generator is an easy-to-use tool for creating a privacy policy for
            blog, website, e-commerce store or mobile app.
          </p>
          <h4>Changes to This Privacy Policy</h4>
          <p>
            We may update our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page.
            We will let you know via email and/or a prominent notice on our
            Service, prior to the change becoming effective and update
            “effective date” at the top of this Privacy Policy. <br /> You are
            advised to review this Privacy Policy periodically for any changes.
            Changes to this Privacy Policy are effective when they are posted on
            this page.
          </p>

          <h4>CONTACT US</h4>
          <div className='contact__us'>
            <p>
              If you have questions about this Opspad Privacy Policy and the
              procedures in effect, please contact our Data Privacy Officer at
              privacy@opspad.com.
            </p>

            <div>Address: </div>
            <div>Ospad office, HNG Project plaza, Lagos, Nigeria. </div>
            <div>
              Or email us at{' '}
              <b style={{ color: '#225ad6', cursor: 'pointer' }}>
                Teamsandpaper@gmail.com
              </b>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default PrivacyPolicy;
